"""Add settings to User

Revision ID: b508e0969913
Revises: d9638c0f95f3
Create Date: 2026-03-24 11:40:19.822447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b508e0969913'
down_revision: Union[str, Sequence[str], None] = 'd9638c0f95f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('theme', sa.String(length=20), server_default='light', nullable=False))
    op.add_column('users', sa.Column('conversation_tone', sa.String(length=50), server_default='neutral', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'conversation_tone')
    op.drop_column('users', 'theme')
    # ### end Alembic commands ###
