"""Initial migration

Revision ID: d9638c0f95f3
Revises: 
Create Date: 2026-03-15 17:44:25.292148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9638c0f95f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_memory')
    op.alter_column('listings', 'ebay_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('listings', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('listings', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('ix_listings_ebay_id'), table_name='listings')
    op.create_index(op.f('ix_listings_ebay_id'), 'listings', ['ebay_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_ebay_id'), table_name='listings')
    op.create_index(op.f('ix_listings_ebay_id'), 'listings', ['ebay_id'], unique=True)
    op.alter_column('listings', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('listings', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('listings', 'ebay_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('user_memory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_memory_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_memory_pkey'))
    )
    # ### end Alembic commands ###
